name: Build & Deploy to GitHub Pages

# run on every push to main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. install Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3. install deps
      - name: Install dependencies
        run: npm ci

      # 4. build your Vite app
      - name: Build
        run: npm run build

      # 5. deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # the branch the action should deploy to.
          # this action will create it if it doesn't exist
          branch: gh-pages
          # folder the action should deploy
          folder: dist
          # cleans out existing files in gh-pages
          clean: true
          # allow the action to push automatically
          token: ${{ secrets.GITHUB_TOKEN }}
